### ISSUE TITLE
Remove settings

### ISSUE THREAD

**Issue by memsharded** [uilianries/conan-catch#1]
For header-only, it doesn't make sense to have settings, you can remove them.

**Comment by uilianries** [comment]
That make sense. Thank's to the tip.

When Catch 1.9.2 was released, the AppVeyor build failed, but Travis was all green.    
Why? There was a bug on that version. So, I released Catch 1.9.2 package for Linux only.
So, I'll need to improve my tests for header-only.

**Comment by memsharded** [comment]
Good!
