### ISSUE TITLE
Request to add the CTest helper

### ISSUE THREAD

**Issue by Ignition** [uilianries/conan-catch#14]
`contrib/ParseAndAddCatchTests.cmake` in Catch's repo is a useful script to populate ctest with the tests defined in catch. I would like to do something like the following using your conan package.

```
add_executable(catch_testsuite tests/tests_for_x.cpp tests/main.cpp)
target_link_libraries(catch_testsuite CONAN_PKG::Catch MYLIB::MYLIB)
enable_testing()
include(${CONAN_CATCH_ROOT}/ParseAndAddCatchTests.cmake)
ParseAndAddCatchTests(catch_testsuite)
```

**Comment by uilianries** [comment]
@Ignition I appreciated your feature request. However, I'm trying to move Conan support for Catch project, as native. You could see [here](https://github.com/philsquared/Catch/issues/926) my recently issue.  
For now, we created a recipe for the project, but is not uploaded to Bintray yet. I'll be very glad if you post this issue in #926 at Catch. We could discuss and implement this issue there.  
Regards.

**Comment by solvingj** [comment]
I'm not sure but is the following issue an even more advanced mechanism for the Catch-CTest integration?

https://github.com/philsquared/Catch/pull/879

**Comment by uilianries** [comment]
Sure, and is very possible to include in the package. However, I prefer move this issue to Catch project. We have created a recipe to be maintained by Catch :)

**Comment by solvingj** [comment]
Actually, I'm saying this issue doesn't even need to go to Catch because Catch already merged in a better version of the feature requested.  In that case, I would say that this issue could simply be closed.
